# Generated by Django 6.0.3 on 2026-03-24 19:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="salaryperiod",
            unique_together={("user", "month", "year")},
        ),
    ]
